import test from 'node:test';
import assert from 'node:assert/strict';
import { Readable } from 'node:stream';
import { BODY_LIMIT, createContactHandler, createLimiter } from '../server/contact-core.mjs';

const valid = { name: 'Test Founder', email: 'founder@example.test', company: 'Test Company', message: 'I would like to discuss a useful product idea.', website: '', submissionId: 'f51fe04c-adb7-4ec2-a82d-19656690919d' };
const env = { RESEND_API_KEY: 'test-only-key', CONTACT_FROM: 'contact@1118.io', CONTACT_TO: 'recipient@example.test', VERCEL_URL: '1118-review.vercel.app' };
function request(body = valid, overrides = {}) { return { method: 'POST', headers: { origin: 'https://1118.io', 'content-type': 'application/json', 'x-vercel-forwarded-for': '192.0.2.1', ...overrides.headers }, body, ...Object.fromEntries(Object.entries(overrides).filter(([key]) => key !== 'headers')) }; }
async function run(req, options = {}) { const headers = {}; let payload; const response = { setHeader: (key, value) => { headers[key] = value; }, end: value => { payload = JSON.parse(value); }, statusCode: 0 }; await createContactHandler({ env, send: async () => ({ ok: true, json: async () => ({ id: 'provider-test-id' }) }), ...options })(req, response); return { status: response.statusCode, payload, headers }; }

test('valid request is accepted only after provider returns an id; envelope is server-owned', async () => {
 let calls = 0; const result = await run(request({ ...valid, to: 'attacker@example.test', from: 'attacker@example.test' }), { send: async (url, options) => { calls++; assert.equal(url, 'https://api.resend.com/emails'); const body = JSON.parse(options.body); assert.deepEqual(body.to, [env.CONTACT_TO]); assert.equal(body.from, `1118 <${env.CONTACT_FROM}>`); assert.equal(body.reply_to, valid.email); assert.equal(options.headers['Idempotency-Key'], `1118-contact-${valid.submissionId}`); assert.equal(body.html, undefined); return { ok: true, json: async () => ({ id: 'test-id' }) }; } }); assert.equal(calls, 1); assert.equal(result.status, 202); assert.equal(result.payload.ok, true); assert.equal(JSON.stringify(result.payload).includes(env.CONTACT_TO), false);
});
test('missing delivery configuration fails honestly without a network request', async () => { const result = await run(request(), { env: {}, send: async () => assert.fail('Must not send') }); assert.equal(result.status, 503); assert.equal(result.payload.ok, false); });
test('invalid fields and email-header injection are rejected before delivery', async () => { for(const change of [{ email: 'user@example.test\r\nBcc:other@example.test' }, { name: 'a' }, { company: 'a'.repeat(161) }, { message: 'short' }, { message: 'x'.repeat(5001) }, { submissionId: 'arbitrary' }]) { const result = await run(request({ ...valid, ...change }), { send: async () => assert.fail('Must not send') }); assert.equal(result.status, 422); }});
test('honeypot returns a rejection, never fabricated success', async () => { const result = await run(request({ ...valid, website: 'bot-filled' }), { send: async () => assert.fail('Must not send') }); assert.equal(result.status, 422); assert.equal(result.payload.ok, false); });
test('cross-origin, missing origin, wrong method and content type cannot send', async () => { for(const [change, status] of [[{ headers: { origin: 'https://other.example' } }, 403], [{ headers: { origin: '' } }, 403], [{ headers: { 'sec-fetch-site': 'cross-site' } }, 403], [{ method: 'GET' }, 405], [{ headers: { 'content-type': 'text/plain' } }, 415]]) { const result=await run(request(valid, change), { send: async()=>assert.fail('Must not send') }); assert.equal(result.status,status); }});
test('current Vercel deployment origin works without opening arbitrary preview origins', async () => { assert.equal((await run(request(valid, { headers: { origin: 'https://1118-review.vercel.app' } }))).status, 202); assert.equal((await run(request(valid, { headers: { origin: 'https://unrelated.vercel.app' } }))).status, 403); });
test('oversized declared, parsed, and streamed bodies are bounded', async () => { assert.equal((await run(request(valid, { headers: { 'content-length': String(BODY_LIMIT + 1) } }))).status, 413); assert.equal((await run(request({ ...valid, message: 'x'.repeat(BODY_LIMIT) }))).status, 413); const stream=Readable.from(['x'.repeat(BODY_LIMIT), 'extra']); Object.assign(stream,{method:'POST',headers:request().headers}); assert.equal((await run(stream)).status,413); });
test('malformed JSON is a 400 and parsed arrays are rejected', async () => { assert.equal((await run(request('{broken'))).status,400); assert.equal((await run(request([]))).status,422); });
test('provider failure, invalid response, and timeout never become a success', async () => { for (const send of [async()=>({ok:false,json:async()=>({error:'private provider error'})}), async()=>({ok:true,json:async()=>({})}),async()=>{throw Error('private timeout')}]) {const result=await run(request(),{send});assert.equal(result.status,503);assert.equal(result.payload.ok,false);assert.equal(JSON.stringify(result.payload).includes('private'),false);} });
test('retry retains a deterministic provider idempotency key', async () => { const keys=[]; const send=async(_,options)=>{keys.push(options.headers['Idempotency-Key']);return{ok:true,json:async()=>({id:'test'})}}; await run(request(),{send}); await run(request(),{send});assert.equal(keys[0],keys[1]); });
test('IP and global per-instance windows limit sends and expire', () => {let time=1000;const limiter=createLimiter({now:()=>time});for(let n=0;n<5;n++)assert.equal(limiter('ip1'),true);assert.equal(limiter('ip1'),false);for(let n=0;n<25;n++)assert.equal(limiter(`ip${n+2}`),true);assert.equal(limiter('other'),false);time+=3_600_000;assert.equal(limiter('ip1'),true);});
test('limiter bounded storage fails closed without evicting fresh entries',()=>{let time=1000;const limiter=createLimiter({now:()=>time,maxEntries:2});assert.equal(limiter('one'),true);assert.equal(limiter('two'),true);assert.equal(limiter('three'),false);time+=3_600_000;assert.equal(limiter('three'),true);});
test('rate response is 429 with retry guidance and no delivery', async()=>{const result=await run(request(),{allowRequest:()=>false,send:async()=>assert.fail('Must not send')});assert.equal(result.status,429);assert.equal(result.headers['Retry-After'],'3600');});
test('Formspree relay uses only configured form and preserves no recipient in payload', async()=>{let called=0;const result=await run(request({...valid,formId:'attacker',to:'attacker@example.test'}),{env:{FORMSPREE_FORM_ID:'abcdefgh'},send:async(url,options)=>{called++;assert.equal(url,'https://formspree.io/f/abcdefgh');assert.equal(options.headers.Accept,'application/json');const body=JSON.parse(options.body);assert.equal(body.email,valid.email);assert.equal(body.to,undefined);assert.equal(body.formId,undefined);return{ok:true,json:async()=>({ok:true})}}});assert.equal(called,1);assert.equal(result.status,202);});
test('invalid Formspree configuration or upstream response fails closed',async()=>{assert.equal((await run(request(),{env:{...env,FORMSPREE_FORM_ID:'https://evil.example/f/abcdefgh'},send:async()=>assert.fail('Must not send')})).status,503);for(const payload of [{}, {ok:false}, {next:'https://example.test/captcha'}])assert.equal((await run(request(),{env:{FORMSPREE_FORM_ID:'abcdefgh'},send:async()=>({ok:true,json:async()=>payload})})).status,503);});
test('concurrent and accepted Formspree retries deduplicate on a warm instance',async()=>{let count=0;const handler=createContactHandler({env:{FORMSPREE_FORM_ID:'abcdefgh'},allowRequest:()=>true,send:async()=>{count++;await new Promise(resolve=>setTimeout(resolve,5));return{ok:true,json:async()=>({ok:true})}}});const invoke=async(body)=>{const response={setHeader(){},end(value){this.body=JSON.parse(value)},statusCode:0};await handler(request(body),response);return response;};const results=await Promise.all([invoke(valid),invoke(valid)]);assert.equal(count,1);assert.equal(results[0].statusCode,202);assert.equal(results[1].statusCode,202);assert.equal((await invoke(valid)).statusCode,202);assert.equal(count,1);assert.equal((await invoke({...valid,message:'A different message with the same idempotency key.'})).statusCode,409);});
