import test from 'node:test';
import assert from 'node:assert/strict';
import { Readable } from 'node:stream';
import { BODY_LIMIT, createContactHandler, createLimiter } from '../server/contact-core.mjs';

const valid = { name: 'Test Founder', email: 'founder@example.test', company: 'Test Company', stage: 'Idea', turnstileToken: 'real-test-token', message: 'I would like to discuss a useful product idea.', website: '', submissionId: 'f51fe04c-adb7-4ec2-a82d-19656690919d' };
const securityEnv = { VERCEL_ENV: 'production', TURNSTILE_SITE_KEY: 'not-a-real-sitekey-00000000000', TURNSTILE_SECRET_KEY: 'not-a-real-secret-00000000000' };
const verification = async (_, options) => ({ ok: true, json: async () => ({ success: true, hostname: JSON.parse(options.body).response === 'preview-token' ? '1118-review.vercel.app' : '1118.io', action: 'contact' }) });
const env = { ...securityEnv, RESEND_API_KEY: 'test-only-key', CONTACT_FROM: 'contact@1118.io', CONTACT_TO: 'recipient@example.test', VERCEL_URL: '1118-review.vercel.app' };
function request(body = valid, overrides = {}) { return { method: 'POST', headers: { origin: 'https://1118.io', 'content-type': 'application/json', 'x-vercel-forwarded-for': '192.0.2.1', ...overrides.headers }, body, ...Object.fromEntries(Object.entries(overrides).filter(([key]) => key !== 'headers')) }; }
async function run(req, options = {}) { const headers = {}; let payload; const response = { setHeader: (key, value) => { headers[key] = value; }, end: value => { payload = JSON.parse(value); }, statusCode: 0 }; await createContactHandler({ env, verify: verification, send: async () => ({ ok: true, json: async () => ({ id: 'provider-test-id' }) }), ...options })(req, response); return { status: response.statusCode, payload, headers }; }

test('valid request is accepted only after provider returns an id; envelope is server-owned', async () => {
 let calls = 0; const result = await run(request(valid), { send: async (url, options) => { calls++; assert.equal(url, 'https://api.resend.com/emails'); const body = JSON.parse(options.body); assert.deepEqual(body.to, [env.CONTACT_TO]); assert.equal(body.from, `1118 <${env.CONTACT_FROM}>`); assert.equal(body.reply_to, valid.email); assert.equal(options.headers['Idempotency-Key'], `1118-contact-${valid.submissionId}`); assert.equal(body.html, undefined); return { ok: true, json: async () => ({ id: 'test-id' }) }; } }); assert.equal(calls, 1); assert.equal(result.status, 202); assert.equal(result.payload.ok, true); assert.equal(JSON.stringify(result.payload).includes(env.CONTACT_TO), false);
});
test('missing delivery configuration fails honestly without a network request', async () => { const result = await run(request(), { env: {}, send: async () => assert.fail('Must not send') }); assert.equal(result.status, 503); assert.equal(result.payload.ok, false); });
test('invalid fields and email-header injection are rejected before delivery', async () => { for(const change of [{ email: 'user@example.test\r\nBcc:other@example.test' }, { name: 'a' }, { company: 'a'.repeat(161) }, { message: 'short' }, { message: 'x'.repeat(5001) }, { submissionId: 'arbitrary' }, {stage: 'Unvalidated'}]) { const result = await run(request({ ...valid, ...change }), { send: async () => assert.fail('Must not send') }); assert.equal(result.status, 422); }});
test('honeypot returns a rejection, never fabricated success', async () => { const result = await run(request({ ...valid, website: 'bot-filled' }), { send: async () => assert.fail('Must not send') }); assert.equal(result.status, 422); assert.equal(result.payload.ok, false); });
test('cross-origin, missing origin, wrong method and content type cannot send', async () => { for(const [change, status] of [[{ headers: { origin: 'https://other.example' } }, 403], [{ headers: { origin: '' } }, 403], [{ headers: { 'sec-fetch-site': 'cross-site' } }, 403], [{ method: 'GET' }, 405], [{ headers: { 'content-type': 'text/plain' } }, 415]]) { const result=await run(request(valid, change), { send: async()=>assert.fail('Must not send') }); assert.equal(result.status,status); }});
test('Production rejects even its Vercel deployment origin', async () => { assert.equal((await run(request(valid, { headers: { origin: 'https://1118-review.vercel.app' } }))).status, 403); });
test('oversized declared, parsed, and streamed bodies are bounded', async () => { assert.equal((await run(request(valid, { headers: { 'content-length': String(BODY_LIMIT + 1) } }))).status, 413); assert.equal((await run(request({ ...valid, message: 'x'.repeat(BODY_LIMIT) }))).status, 413); const stream=Readable.from(['x'.repeat(BODY_LIMIT), 'extra']); Object.assign(stream,{method:'POST',headers:request().headers}); assert.equal((await run(stream)).status,413); });
test('malformed JSON is a 400 and parsed arrays are rejected', async () => { assert.equal((await run(request('{broken'))).status,400); assert.equal((await run(request([]))).status,422); });
test('provider failure, invalid response, and timeout never become a success', async () => { for (const send of [async()=>({ok:false,json:async()=>({error:'private provider error'})}), async()=>({ok:true,json:async()=>({})}),async()=>{throw Error('private timeout')}]) {const result=await run(request(),{send});assert.equal(result.status,503);assert.equal(result.payload.ok,false);assert.equal(JSON.stringify(result.payload).includes('private'),false);} });
test('retry retains a deterministic provider idempotency key', async () => { const keys=[]; const send=async(_,options)=>{keys.push(options.headers['Idempotency-Key']);return{ok:true,json:async()=>({id:'test'})}}; await run(request(),{send}); await run(request(),{send});assert.equal(keys[0],keys[1]); });
test('IP and global per-instance windows limit sends and expire', () => {let time=1000;const limiter=createLimiter({now:()=>time});for(let n=0;n<5;n++)assert.equal(limiter('ip1'),true);assert.equal(limiter('ip1'),false);for(let n=0;n<25;n++)assert.equal(limiter(`ip${n+2}`),true);assert.equal(limiter('other'),false);time+=3_600_000;assert.equal(limiter('ip1'),true);});
test('limiter bounded storage fails closed without evicting fresh entries',()=>{let time=1000;const limiter=createLimiter({now:()=>time,maxEntries:2});assert.equal(limiter('one'),true);assert.equal(limiter('two'),true);assert.equal(limiter('three'),false);time+=3_600_000;assert.equal(limiter('three'),true);});
test('rate response is 429 with retry guidance and no delivery', async()=>{const result=await run(request(),{allowRequest:()=>false,send:async()=>assert.fail('Must not send')});assert.equal(result.status,429);assert.equal(result.headers['Retry-After'],'3600');});
test('Formspree is never used as a silent fallback', async () => { const result = await run(request(), {env: {...securityEnv, FORMSPREE_FORM_ID:'abcdefgh'}, send: async()=>assert.fail('No fallback')}); assert.equal(result.status,503); });
test('Resend stays selected with legacy Formspree configuration present', async()=>{let calls=0; const result=await run(request(),{env:{...env,FORMSPREE_FORM_ID:'abcdefgh'},send:async(url)=>{assert.equal(url,'https://api.resend.com/emails');calls++;return{ok:true,json:async()=>({id:'test'})}}});assert.equal(result.status,202);assert.equal(calls,1);});
test('unknown properties and wrong field types are rejected',async()=>{for(const change of [{to:'attacker@example.test'},{company:{}},{links:12},{website:false}])assert.equal((await run(request({...valid,...change}))).status,422);});
test('optional links only accept bounded HTTP URLs and are never fetched',async()=>{for(const links of ['javascript:alert(1)','file:///etc/passwd','https://user:password@example.test','https://example.test/'+ 'a'.repeat(2048)])assert.equal((await run(request({...valid,links}))).status,422);let calls=0;const result=await run(request({...valid,links:'https://example.test/brief'}),{send:async(url,options)=>{calls++;assert.equal(url,'https://api.resend.com/emails');assert.match(JSON.parse(options.body).text,/https:\/\/example.test\/brief/);return{ok:true,json:async()=>({id:'test'})}}});assert.equal(result.status,202);assert.equal(calls,1);});
test('async limiter rejects and store failures fail closed',async()=>{assert.equal((await run(request(),{allowRequest:async()=>false})).status,429);assert.equal((await run(request(),{allowRequest:async()=>{throw Error('private storage')}})).status,503);});
test('Preview ignores production keys and inbox, requiring separate delivery credentials',async()=>{const preview={...env,VERCEL_ENV:'preview'};const req=request(valid,{headers:{origin:'https://1118-review.vercel.app'}});const verify=async()=>({ok:true,json:async()=>({success:true,metadata:{result_with_testing_key:true}})});assert.equal((await run(req,{env:preview,verify})).status,503);let recipient;const result=await run(req,{env:{...preview,CONTACT_PREVIEW_RESEND_API_KEY:'preview-key',CONTACT_PREVIEW_FROM:'test@1118.io'},verify,send:async(_,options)=>{recipient=JSON.parse(options.body).to;assert.equal(options.headers.Authorization,'Bearer preview-key');return{ok:true,json:async()=>({id:'test'})}}});assert.equal(result.status,202);assert.deepEqual(recipient,['delivered@resend.dev']);});
test('concurrent retries coalesce and changed payload with the same id is rejected',async()=>{let count=0;const handler=createContactHandler({verify:verification,env,allowRequest:()=>true,send:async()=>{count++;await new Promise(resolve=>setTimeout(resolve,5));return{ok:true,json:async()=>({id:'test'})}}});const invoke=async(body)=>{const response={setHeader(){},end(value){this.body=JSON.parse(value)},statusCode:0};await handler(request(body),response);return response;};const results=await Promise.all([invoke(valid),invoke(valid)]);assert.equal(count,1);assert.equal(results[0].statusCode,202);assert.equal(results[1].statusCode,202);assert.equal((await invoke(valid)).statusCode,202);assert.equal(count,1);assert.equal((await invoke({...valid,message:'A different message with the same idempotency key.'})).statusCode,409);});
