// Offline derivative generation; production has no Sharp dependency.
const { default: sharp } = await import(process.env.SHARP_MODULE || 'sharp');
import fs from 'node:fs';import path from 'node:path';import { createHash } from 'node:crypto';
const dir='src/assets/responsive';fs.mkdirSync(dir,{recursive:true});
const files=[...['laurie-source.jpg','laurie-result.webp','sloane-source.webp','sloane-result.webp','sloane-square-1024.webp','sloane-profile-640x800.webp','sloane-circle-640.webp','elise-source.webp','elise-result.webp','rowan-result.webp','theo-result.webp','graham-result.webp'].map(x=>'portrait/'+x),...['pippin-bill.jpg','ernestine-jennifer.jpg','lola-aj.jpg','griffey-skyler.jpg'].map(x=>'reviews-engine/current/'+x),'property-insights/product-showroom-home.webp','signal/signal-workstation-authentic-composite-20260913.webp','signal/signal-archival-interface.png','signal/signal-historical-data-2019.png','signal/signal-manage-structures-2019.png'];
const imports=[],objects=[],inventory=[];
for(const [i,name] of files.entries()){const src='src/assets/showcase/'+name,meta=await sharp(src).metadata(),stem=path.basename(name,path.extname(name)),max=meta.width;imports.push(`import original${i} from '../assets/showcase/${name}';`);const sets={avif:[],webp:[]},rows=[];const widths=[...new Set([...(name.includes('profile') || name.includes('circle') ? [256,384] : []),480,768,1024,...(name.startsWith('signal/')?[1440]:[]),max].filter(w=>w<=max))].sort((a,b)=>a-b);for(const w of widths){for(const fmt of ['avif','webp']){const out=`${dir}/${stem}-${w}.${fmt}`,id=`image${i}_${w}_${fmt}`,screen=name.startsWith('signal/');await sharp(src).resize({width:w,withoutEnlargement:true})[fmt](fmt==='avif'?{quality:screen?82:name==='portrait/laurie-result.webp'?65:72,effort:6,chromaSubsampling:'4:4:4'}:{quality:screen?94:88,effort:6}).toFile(out);const useOriginal = fmt==='webp' && meta.format==='webp' && w===max && fs.statSync(out).size >= fs.statSync(src).size; if (!useOriginal) imports.push(`import ${id} from '../assets/responsive/${path.basename(out)}';`);sets[fmt].push(`\${${useOriginal ? 'original'+i : id}} ${w}w`);rows.push({width:w,format:fmt,bytes:fs.statSync(out).size});}}
objects.push(`  [original${i}]: { avif: \`${sets.avif.join(', ')}\`, webp: \`${sets.webp.join(', ')}\` }`);inventory.push({source:src,sha256:createHash('sha256').update(fs.readFileSync(src)).digest('hex'),width:meta.width,height:meta.height,format:meta.format,bytes:fs.statSync(src).size,derivatives:rows});console.log(stem,fs.statSync(src).size,'→',rows.filter(x=>x.width===max).map(x=>x.format+':'+x.bytes).join(' '));}
fs.writeFileSync('src/content/responsive-images.ts','// Generated from approved originals; see docs/FOUNDER-POLISH-20260914.md.\n'+imports.join('\n')+'\nexport const responsiveImages: Record<string,{avif:string;webp:string}> = {\n'+objects.join(',\n')+'\n};\n');fs.writeFileSync('docs/image-delivery-20260914.json',JSON.stringify(inventory,null,2));

for (const [src,name] of [['src/assets/showcase/portrait/portrait-native-icon.png','portrait-icon'],['src/assets/showcase/reviews-engine/reviews-engine-shield-primary.png','reviews-shield'],['src/assets/showcase/property-insights/brand/property-insights-mark.png','property-mark']]) await sharp(src).resize({width:256,height:256,fit:'inside',withoutEnlargement:true}).webp({lossless:true,effort:6}).toFile(dir+'/'+name+'.webp');
